spring:
  application:
    name: composer

composer:
  services:
    user-service: http://localhost:8081/api
    order-service: http://localhost:8081/order-service
    item-service: http://item-service:8081/api
  client:
    id: 7srxgYG8u52QXDwatb
    secret: rAVKKNBmMN64Bjvf8PcZv5YJgZSvZv4a

server:
  port:8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
